S = set()
n = int(input("Enter number : "))
S.add(n)
n = int(input("Enter number : "))
S.add(n)
n = int(input("Enter number : "))
S.add(n)
n = int(input("Enter number : "))
S.add(n)
n = int(input("Enter number : "))
S.add(n)
n = int(input("Enter number : "))
S.add(n)
n = int(input("Enter number : "))
S.add(n)
n = int(input("Enter number : "))
S.add(n)
print(S)